### ISSUE TITLE
Label file - interpretation

### ISSUE THREAD

**Issue by TejasT** [keshik6/KITTI-2d-object-detection#1]
Hi,
I wanted to know how were the label values generated in the label files (..../master/data/train/yolo_labels), from the original kitti label files? Is it some sort of scaling wrt. to the image dimensions? 
regards, Tejas

**Comment by keshik6** [comment]
Hi, 
It is just a format conversion. Please refer to this repo 
https://github.com/ssaru/convert2Yolo

Hope this clarifies.

Regards
Keshik

**Comment by TejasT** [comment]
Oh OK. Understood, thanks!

Regards,
Tejas
