### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by vaibhavmaheshwari19** [keshik6/KITTI-2d-object-detection#2]
Hi, 
1) I want to know if there is any benchmark score present for this code as there is in kitti website.
2) Have you implemented the model on a video, if not can you tell me how to do that

**Comment by keshik6** [comment]
Hi,
Sorry for the delayed reply. 
1. This work was part of using synthetic images to train yolo. So the mAP score for the kitti dataset is not available.
2. I haven't tried on video. But if you want to do it, consider video as a sequence of frames. So you can predict on individual frames and then concatenate them to get the prediction footage.

Thanks.
