### ISSUE TITLE
Output images are smaller than input?

### ISSUE THREAD

**Issue by martindisley** [keshik6/KITTI-2d-object-detection#3]
Hello, 

Thanks for making this repo available and for opening sourcing your pre-trained weights. I'm looking to run `detect.py` on some of my own images and I'm wondering if there is any way to preserve the resolution of the input images?

Right now it looks like they come out a quarter of the size they were?

Any help would be much appreciated.

Cheers

**Comment by keshik6** [comment]
Hi,
A simple way to check this would be to verify the size of images returned by the dataset object

`` dataset_test = ImageFolder("../data/samples/", img_size=416)``
``path, image = dataset_test.__getitem__(0)``

You can check the size of the image.
